# Codecov configuration for REvoCompute
# https://docs.codecov.com/docs/codecovyml-reference

flags:
  server:
    paths:
      - revocompute/
    carryforward: false

coverage:
  status:
    project:
      server:
        target: auto
        threshold: 1%
        flags:
          - server

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_head: yes
  show_carryforward_flags: false

github_checks:
  annotations: true
