api_version: 1
id: opendde
version: '1'
runtime:
  image: /mnt/data/srv/revodesign/server-slurm/images/opendde_v1.sif
  definition: opendde.def
  dockerfile: Dockerfile
  entrypoint:
  - bash
  - /app/revocompute/run.sh
tasks:
- tasks/opendde/task.yaml
contributions:
  input_workspace_plugins:
  - jaag-builder
configuration_schemas:
  input_workspace:
    jaag-builder:
      type: object
      additionalProperties: false
      properties:
        target:
          type: string
          enum: [alphafold3, opendde]
