identifier: gremlin-lh-result
entrypoint: ./index.js
requires:
  - summary
  - mrf_model
  - profile
  - alignment_statistics
  - model_metadata
  - pairwise_scores
  - raw_matrix
  - apc_matrix
optional:
  - query
  - alignment
  - sequence_weights
  - training_history
  - sequence_scores
  - coupling_plot
