api_version: 1
id: colabfold_af2
version: '1'
runtime:
  docker_image: revodesign-revocompute-runner-colabfold_af2
  slurm_image: /mnt/data/srv/revodesign/server-slurm/images/colabfold_af2_v1.sif
  definition: colabfold_af2.def
  dockerfile: Dockerfile
  entrypoint:
  - bash
  - /app/revocompute/run.sh
tasks:
- tasks/colabfold_af2/task.yaml
