/* Foundry RoseTTAFold3 seed/sample confidence composition. */
/* SPDX-License-Identifier: GPL-3.0-only */

const STYLE = `.rf3-result{display:grid;gap:1rem;padding:1rem}.rf3-result h2,.rf3-result h3,.rf3-result p{margin:0}.rf3-section{display:grid;gap:.55rem;min-width:0}.rf3-candidates,.rf3-actions,.rf3-downloads{display:flex;flex-wrap:wrap;gap:.45rem}.rf3-candidates button[aria-current="true"]{outline:2px solid var(--accent);outline-offset:2px}.rf3-columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,26rem),1fr));gap:1rem}.rf3-figure{position:relative;overflow:hidden}.rf3-figure canvas{display:block;max-width:100%}.rf3-figure .pair-matrix-label{position:absolute;color:var(--muted);font-size:11px}.rf3-figure .af3-label-x{transform:translateX(-50%)}.rf3-figure .af3-label-y{transform:translateY(-50%)}.rf3-figure .af3-title{color:var(--ink);font-size:12px}.rf3-figure .af3-title-y{transform:translate(-50%,-50%) rotate(-90deg);white-space:nowrap}`;
function list(value) { return Array.isArray(value) ? value : value ? [value] : []; }
function section(title, note) { const node = document.createElement("section"); node.className = "rf3-section"; const heading = document.createElement("h3"); heading.textContent = title; node.appendChild(heading); if (note) { const text = document.createElement("p"); text.className = "scientific-note"; text.textContent = note; node.appendChild(text); } return node; }
function message(value) { const node = document.createElement("p"); node.className = "preview-message"; node.textContent = value; return node; }
async function response(url, signal) { const value = window.REvoDesignAuth ? await window.REvoDesignAuth.authFetch(url, { signal }) : await fetch(url, { credentials: "same-origin", signal }); if (!value.ok) throw new Error("RF3 evidence could not be loaded."); return value; }
async function json(url, signal) { return (await response(url, signal)).json(); }
function identity(name, suffix) { const match = String(name || "").match(new RegExp("^(.*)_seed-(\\d+)_sample-(\\d+)_" + suffix + "$")); return match ? { target: match[1], seed: Number(match[2]), sample: Number(match[3]), key: match[1] + ":" + match[2] + ":" + match[3] } : null; }
function matching(files, candidate, suffix) { const wanted = String(candidate.name || "").replace(/_model\.cif$/, suffix); return files.find((file) => file.name === wanted) || null; }
async function projection(artifact, key, signal) { if (!artifact || !artifact.ndarray_url) return null; try { return await window.REvoComputeScientific.loadNumericProjection(artifact, { key, signal }); } catch (error) { if (signal && signal.aborted) throw error; return null; } }
function square(value) { if (!value || value.shape.length !== 2 || value.shape[0] !== value.shape[1] || value.values.length !== value.shape[0] * value.shape[1]) return null; const rows = []; for (let offset = 0; offset < value.values.length; offset += value.shape[1]) rows.push(value.values.slice(offset, offset + value.shape[1])); return rows; }
function rankingRows(text, target) { const lines = String(text).trim().split(/\r?\n/); if (lines.shift() !== "seed,sample,ranking_score") return []; return lines.map((line) => { const cells = line.split(","); const seed = Number(cells[0]); const sample = Number(cells[1]); const score = Number(cells[2]); return Number.isInteger(seed) && Number.isInteger(sample) && Number.isFinite(score) ? { key: target + ":" + seed + ":" + sample, score } : null; }).filter(Boolean); }

export default { async mount(host, context) {
  const S = window.REvoComputeScientific; if (!S) throw new Error("Scientific result components are unavailable.");
  const structures = list(context.files.get("structures")); const summaries = list(context.files.get("summaries")); const confidences = list(context.files.get("confidences")); const rankings = list(context.files.get("rankings")); const runRecord = list(context.files.get("run_record"))[0]; const modelAssets = list(context.files.get("model_assets"))[0]; let local = null; let matrix = null;
  const scores = new Map(); for (const artifact of rankings) { const match = String(artifact.name || "").match(/^(.*)_ranking_scores\.csv$/); if (!match) continue; const rows = rankingRows(await (await response(artifact.url)).text(), match[1]); rows.forEach((row) => scores.set(row.key, row.score)); }
  structures.sort((left, right) => { const a = identity(left.name, "model\\.cif"); const b = identity(right.name, "model\\.cif"); return (scores.get(b && b.key) ?? -Infinity) - (scores.get(a && a.key) ?? -Infinity) || String(left.name).localeCompare(String(right.name)); });
  const root = document.createElement("div"); root.className = "rf3-result"; const style = document.createElement("style"); style.textContent = STYLE; const heading = document.createElement("h2"); heading.textContent = "RoseTTAFold3 prediction"; root.append(style, heading);
  const downloads = document.createElement("div"); downloads.className = "rf3-downloads"; [["Download run record", runRecord], ["Download model identity", modelAssets]].forEach(([label, artifact]) => { const button = document.createElement("button"); button.type = "button"; button.className = "btn btn-soft"; button.textContent = label; button.addEventListener("click", () => context.services.downloadFile(artifact)); downloads.appendChild(button); }); root.appendChild(downloads);
  const candidates = section("Ranked samples", "Descending published ranking score; target, seed, and sample remain explicit."); const candidateHost = document.createElement("div"); candidateHost.className = "rf3-candidates"; const actions = document.createElement("div"); actions.className = "rf3-actions"; candidates.append(candidateHost, actions); root.appendChild(candidates);
  const columns = document.createElement("div"); columns.className = "rf3-columns"; const metrics = section("Prediction confidence", "Published summary values for the selected sample."); const metricHost = document.createElement("div"); metrics.appendChild(metricHost); const confidence = section("Atom confidence", "Per-atom pLDDT on RF3's persisted 0 to 1 scale."); const confidenceHost = document.createElement("div"); confidence.appendChild(confidenceHost); columns.append(metrics, confidence); root.appendChild(columns);
  const pae = section("Predicted aligned error", "Token-pair PAE in angstroms; lower is better."); const figure = document.createElement("div"); figure.className = "rf3-figure"; const canvas = document.createElement("canvas"); canvas.tabIndex = 0; canvas.setAttribute("role", "grid"); const readout = document.createElement("p"); readout.className = "matrix-readout"; readout.setAttribute("role", "status"); figure.appendChild(canvas); pae.append(figure, readout); root.appendChild(pae); host.replaceChildren(root);
  matrix = new S.PairMatrix({ figure, canvas, readout, minimum: 0, unit: "angstrom", xTitle: "Aligned token", yTitle: "Scored token", legendTitle: "PAE", decimals: 1 });
  async function select(structure, index, request) {
    actions.replaceChildren(); const open = document.createElement("button"); open.type = "button"; open.className = "btn btn-soft"; open.textContent = "Open selected structure"; open.addEventListener("click", () => context.services.openFile(structure)); actions.appendChild(open);
    const summaryFile = matching(summaries, structure, "_summary_confidences.json"); const confidenceFile = matching(confidences, structure, "_confidences.json"); const [summary, plddt, paeValue] = await Promise.all([summaryFile ? json(summaryFile.url, request.signal) : null, projection(confidenceFile, "atom_plddts", request.signal), projection(confidenceFile, "pae", request.signal)]); if (!request.current()) return;
    if (summary) new S.ScalarMetricGrid(metricHost, [{ label: "Overall pLDDT", value: summary.overall_plddt, unit: "score", meaning: "Higher is better" }, { label: "Overall PAE", value: summary.overall_pae, unit: "angstrom", meaning: "Lower is better" }, { label: "Overall PDE", value: summary.overall_pde, unit: "angstrom", meaning: "Lower is better" }, { label: "pTM", value: summary.ptm, unit: "score", meaning: "Higher is better" }, { label: "ipTM", value: summary.iptm, unit: "score", meaning: "Higher is better" }, { label: "Ranking score", value: summary.ranking_score, unit: "score", meaning: "Higher is better" }, { label: "Clash", value: summary.has_clash ? "Yes" : "No" }]); else metricHost.replaceChildren(message("Summary confidence was not published for this sample."));
    if (local) local.destroy(); if (plddt && plddt.shape.length === 1) local = new S.LocalConfidenceSeries(confidenceHost, { series: [{ label: "Atom pLDDT", values: plddt.values }], xLabel: "Atom index", yLabel: "pLDDT", unit: "score", direction: "higher is better", yMin: 0, yMax: 1 }); else confidenceHost.replaceChildren(message("Atom pLDDT is unavailable or exceeds the bounded interactive limit."));
    const values = square(paeValue); if (!values) { figure.hidden = true; readout.textContent = "PAE is unavailable or exceeds the bounded interactive limit."; return; } figure.hidden = false; const labels = values.map((_, item) => String(item + 1)); matrix.setData({ values, xLabels: labels, yLabels: labels });
  }
  const selector = new S.CandidateSelector(candidateHost, { items: structures, label: (item) => { const itemIdentity = identity(item.name, "model\\.cif"); const score = itemIdentity ? scores.get(itemIdentity.key) : null; return itemIdentity ? itemIdentity.target + " · seed " + itemIdentity.seed + " · sample " + itemIdentity.sample + (score == null ? "" : " · " + score) : String(item.name || "Sample"); }, onSelect: select }); if (structures.length) await selector.select(0); else candidateHost.replaceChildren(message("RF3 published early-stopping metrics without a structure."));
  return { destroy() { selector.destroy(); if (local) local.destroy(); matrix.destroy(); } };
} };
