api_version: 1
id: freebindcraft
version: '1'
runtime:
  docker_image: revodesign-revocompute-runner-freebindcraft
  image_artifact: freebindcraft_v1.sif
  definition: freebindcraft.def
  dockerfile: Dockerfile
  entrypoint:
  - bash
  - /app/revocompute/run.sh
tasks:
- tasks/freebindcraft/task.yaml
