mounts:
  - host_path: "/mnt/db/weights/easifa2"
    container_path: "/mnt/db/weights/easifa2"
    mode: "ro"
  - host_path: "/mnt/db/weights/esm/checkpoints"
    container_path: "/mnt/models/torch/hub/checkpoints"
    mode: "ro"
env:
  TORCH_HOME: "/mnt/models/torch"
max_runtime_seconds: 3600
