/* Boltz scientific result composition using bounded ndarray projections. */
/* SPDX-License-Identifier: GPL-3.0-only */

const STYLE = `.boltz-result{display:grid;gap:1rem;padding:1rem}.boltz-result h2,.boltz-result h3,.boltz-result p{margin:0}.boltz-section{display:grid;gap:.55rem;min-width:0}.boltz-candidates,.boltz-actions{display:flex;flex-wrap:wrap;gap:.45rem}.boltz-candidates button[aria-current="true"]{outline:2px solid var(--accent);outline-offset:2px}.boltz-columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,26rem),1fr));gap:1rem}.boltz-figure{position:relative;overflow:hidden}.boltz-figure canvas{display:block;max-width:100%}.boltz-figure .pair-matrix-label{position:absolute;color:var(--muted);font-size:11px}.boltz-figure .af3-label-x{transform:translateX(-50%)}.boltz-figure .af3-label-y{transform:translateY(-50%)}.boltz-figure .af3-title{color:var(--ink);font-size:12px}.boltz-figure .af3-title-y{transform:translate(-50%,-50%) rotate(-90deg);white-space:nowrap}`;
function list(value){return Array.isArray(value)?value:value?[value]:[]} function section(title,note){const n=document.createElement("section");n.className="boltz-section";const h=document.createElement("h3");h.textContent=title;n.appendChild(h);if(note){const p=document.createElement("p");p.className="scientific-note";p.textContent=note;n.appendChild(p)}return n} function message(value){const p=document.createElement("p");p.className="preview-message";p.textContent=value;return p}
async function json(url,signal){const r=window.REvoDesignAuth?await window.REvoDesignAuth.authFetch(url,{signal}):await fetch(url,{credentials:"same-origin",signal});if(!r.ok)throw new Error("Boltz evidence could not be loaded.");return r.json()}
async function ndarray(artifact,key,signal){if(!artifact||!artifact.ndarray_url)return null;try{return await window.REvoComputeScientific.loadNumericProjection(artifact,{key,signal})}catch(error){if(signal&&signal.aborted)throw error;return null}}
function reshape(value){if(!value||value.shape.length!==2||value.shape[0]!==value.shape[1]||value.values.length!==value.shape[0]*value.shape[1])return null;const width=value.shape[1],rows=[];for(let i=0;i<value.values.length;i+=width)rows.push(value.values.slice(i,i+width));return rows}
export default{async mount(host,context){const S=window.REvoComputeScientific;if(!S)throw new Error("Scientific result components are unavailable.");const structures=list(context.files.get("structures")),summaries=list(context.files.get("summaries")),locals=list(context.files.get("local_confidence")),paes=list(context.files.get("pae")),pdes=list(context.files.get("pde"));const requiredAligned=summaries.length===structures.length&&locals.length===structures.length,paeAligned=!paes.length||paes.length===structures.length,pdeAligned=!pdes.length||pdes.length===structures.length;let local=null,paeMatrix=null,pdeMatrix=null;
const root=document.createElement("div");root.className="boltz-result";const style=document.createElement("style");style.textContent=STYLE;const h=document.createElement("h2");h.textContent="Boltz prediction";const intro=document.createElement("p");intro.textContent="Confidence-ranked structures with bounded per-token and pairwise confidence projections.";root.append(style,h,intro);const candidates=section("Ranked models","Candidate order follows Boltz model rank.");const candidateHost=document.createElement("div");candidateHost.className="boltz-candidates";const actions=document.createElement("div");actions.className="boltz-actions";candidates.append(candidateHost,actions);root.appendChild(candidates);const columns=document.createElement("div");columns.className="boltz-columns";const metrics=section("Structure confidence","Published metrics for the selected model.");const metricHost=document.createElement("div");metrics.appendChild(metricHost);const confidence=section("Local confidence","Per-token pLDDT on Boltz's persisted 0 to 1 scale.");const confidenceHost=document.createElement("div");confidence.appendChild(confidenceHost);columns.append(metrics,confidence);root.appendChild(columns);
function matrixSection(title,note){const group=section(title,note),figure=document.createElement("div");figure.className="boltz-figure";const canvas=document.createElement("canvas");canvas.tabIndex=0;canvas.setAttribute("role","grid");const readout=document.createElement("p");readout.className="matrix-readout";readout.setAttribute("role","status");figure.appendChild(canvas);group.append(figure,readout);root.appendChild(group);return{figure,canvas,readout}}const paeView=matrixSection("Predicted aligned error","Optional PAE in angstroms; lower is better."),pdeView=matrixSection("Predicted distance error","Optional PDE in angstroms; lower is better.");host.replaceChildren(root);paeMatrix=new S.PairMatrix({figure:paeView.figure,canvas:paeView.canvas,readout:paeView.readout,minimum:0,unit:"angstrom",xTitle:"Aligned token",yTitle:"Scored token",legendTitle:"PAE",decimals:1});pdeMatrix=new S.PairMatrix({figure:pdeView.figure,canvas:pdeView.canvas,readout:pdeView.readout,minimum:0,unit:"angstrom",xTitle:"Token",yTitle:"Token",legendTitle:"PDE",decimals:1});
    function clearCandidate(text){actions.replaceChildren();metricHost.replaceChildren(message(text));confidenceHost.replaceChildren();if(local){local.destroy();local=null}for(const view of[paeView,pdeView]){view.figure.hidden=true;view.readout.textContent=""}}
    function showPair(projected,files,view,renderer){if(!files.length){view.readout.textContent="Not requested for this run.";return}const values=reshape(projected);if(!values){view.readout.textContent="This array exceeds the bounded interactive limit.";return}view.figure.hidden=false;const labels=values.map((_,i)=>String(i+1));renderer.setData({values,xLabels:labels,yLabels:labels})}
    async function select(structure,index,request){clearCandidate("Loading candidate evidence...");if(!requiredAligned){clearCandidate("Candidate evidence counts do not align.");return}try{const [summary,plddt,pae,pde]=await Promise.all([json(summaries[index].url,request.signal),ndarray(locals[index],"plddt",request.signal),paes.length&&paeAligned?ndarray(paes[index],"pae",request.signal):null,pdes.length&&pdeAligned?ndarray(pdes[index],"pde",request.signal):null]);if(!request.current())return;const open=document.createElement("button");open.type="button";open.className="btn btn-soft";open.textContent="Open selected structure";open.addEventListener("click",()=>context.services.openFile(structure));actions.replaceChildren(open);new S.ScalarMetricGrid(metricHost,[{label:"Confidence score",value:summary.confidence_score,unit:"score",meaning:"Higher is better"},{label:"pTM",value:summary.ptm,unit:"score",meaning:"Higher is better"},{label:"ipTM",value:summary.iptm,unit:"score",meaning:"Higher is better"},{label:"Complex pLDDT",value:summary.complex_plddt,unit:"score",meaning:"Higher is better"},{label:"Complex PDE",value:summary.complex_pde,unit:"distance",meaning:"Lower is better"}]);if(plddt&&plddt.shape.length===1)local=new S.LocalConfidenceSeries(confidenceHost,{series:[{label:"pLDDT",values:plddt.values}],xLabel:"Token index",yLabel:"pLDDT",unit:"score",direction:"higher is better",yMin:0,yMax:1});else confidenceHost.replaceChildren(message("Local pLDDT exceeds the bounded interactive limit."));showPair(pae,paes,paeView,paeMatrix);showPair(pde,pdes,pdeView,pdeMatrix);return true}catch(error){if(error.name!=="AbortError"&&request.current())clearCandidate(error.message||"Boltz evidence could not be loaded.")}}
const selector=new S.CandidateSelector(candidateHost,{items:structures,store:context.selection,label:(_,i)=>"Model "+i,onSelect:select});if(structures.length)await selector.select(0);else candidateHost.replaceChildren(message("No model was published."));return{destroy(){selector.destroy();if(local)local.destroy();paeMatrix.destroy();pdeMatrix.destroy()}}}};
