#!/usr/bin/env python3
# Copyright (c) 2026 The REvoDesign Developers.
# Distributed under the terms of the GNU General Public License v3.0.
# SPDX-License-Identifier: GPL-3.0-only
"""Host-local liaison bus: an append-only mailbox per logical agent.

Independently running agent sessions on one host (Claude Code, Codex, ...) need
to hand each other a few *coordination* facts without a broker: a dependency
merged, a review is available, a heavy-work lease was taken or released, main
advanced. This module is that channel and nothing more.

Design, and its deliberate limits:

* one append-only JSONL *mailbox* per logical agent under a host-local bus
  directory (``<bus>/<agent>.jsonl``), never a database and never a daemon;
* an append is a single ``O_APPEND`` write under ``flock``, so concurrent
  writers cannot interleave or lose a line;
* messages are **data, never commands**: this module never evaluates, executes,
  or shell-interpolates a message body, and it refuses bodies that cannot be
  stored as one JSONL line;
* a message type must come from the small closed vocabulary below; unknown types
  are refused rather than forwarded, so the bus cannot drift into a general
  messaging or RPC surface;
* tmux is a *notification* path only. A notice tells a peer pane that its
  mailbox has something new; the peer reads the mailbox itself. The notice text
  is generated by this module from the mailbox name -- never copied from a
  message body -- and delivery is confirmed by capturing the pane and observing
  it change. Without tmux the bus degrades to mailbox-only with no error.

Where truth lives: durable technical truth belongs in the GitHub PR/thread,
campaign coordination truth belongs to the Commander, and this bus carries only
ephemeral notification between peers. Nothing here is required to reconstruct a
campaign, so losing the bus directory loses nothing durable.

CLI::

    campaign_liaison_bus.py send --from claude-pr69 --to commander \\
        --type CHECKPOINT_READY --pr 69 --message "head 53789f3 is ready"
    campaign_liaison_bus.py read --agent commander --last 20
    campaign_liaison_bus.py peers
"""

from __future__ import annotations

import argparse
import fcntl
import json
import os
import re
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

DEFAULT_BUS_DIR = "/home/yinying/repo/.rc-agent-bus"

# The closed message vocabulary. Each entry is a coordination fact that belongs
# on the bus; anything else belongs in a PR thread (durable) or with the
# Commander (coordination truth).
MESSAGE_TYPES = (
    # Session start: announce the logical agent name and, optionally, a pane.
    "REGISTERED",
    # A dependency PR merged, so a descendant may reconcile.
    "DEPENDENCY_MERGED",
    # A review is available for a peer to act on.
    "REVIEW_AVAILABLE",
    # Main advanced.
    "MAIN_ADVANCED",
    # An owner reached a checkpoint of interest to a peer.
    "CHECKPOINT_READY",
    # Ask a peer to read its PR thread for durable detail.
    "PLEASE_INSPECT",
    # Host heavy-work lease, taken and released.
    "HEAVY_LEASE_ACQUIRED",
    "HEAVY_LEASE_RELEASED",
    # Shared demo deployment target, occupied and free.
    "DEMO_DEPLOYMENT_ACQUIRED",
    "DEMO_DEPLOYMENT_RELEASED",
    "DEMO_DEPLOYMENT_BUSY",
    "DEMO_DEPLOYMENT_FREE",
    # Acknowledges another coordination message.
    "ACK",
)

# Required message keys. ``ts`` is recorded for humans; it is informational and
# never the ordering authority (append order is).
REQUIRED_KEYS = ("id", "from", "to", "type", "message")

AGENT_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}$")
ID_RE = re.compile(r"^[0-9a-f]{32}$")
TMUX_TARGET_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,64}$")
MAX_MESSAGE_CHARS = 512


class BusError(ValueError):
    """A message or request the bus refuses to store or act on."""


def _bus_dir(path=None) -> Path:
    return Path(path or os.environ.get("RC_AGENT_BUS_DIR") or DEFAULT_BUS_DIR)


def mailbox_path(agent: str, bus_dir=None) -> Path:
    if not isinstance(agent, str) or not AGENT_RE.match(agent):
        raise BusError(f"invalid logical agent name: {agent!r}")
    return _bus_dir(bus_dir) / f"{agent}.jsonl"


def _clean_message(body: str) -> str:
    """Validate a message body as storable, single-line data."""
    if not isinstance(body, str):
        raise BusError("message must be a string")
    if "\x00" in body or "\n" in body or "\r" in body:
        raise BusError("message must be a single line without control characters")
    text = body.strip()
    if not text:
        raise BusError("message must not be empty")
    if len(text) > MAX_MESSAGE_CHARS:
        raise BusError(f"message exceeds {MAX_MESSAGE_CHARS} characters")
    return text


def build_message(
    *,
    sender: str,
    recipient: str,
    message_type: str,
    body: str,
    pr=None,
    reply_to=None,
    message_id=None,
) -> dict:
    """Build and validate one bus message. Raises :class:`BusError` otherwise."""
    if not isinstance(sender, str) or not AGENT_RE.match(sender):
        raise BusError(f"invalid sender name: {sender!r}")
    if not isinstance(recipient, str) or not AGENT_RE.match(recipient):
        raise BusError(f"invalid recipient name: {recipient!r}")
    if message_type not in MESSAGE_TYPES:
        raise BusError(f"unknown message type {message_type!r}; allowed: {', '.join(MESSAGE_TYPES)}")
    text = _clean_message(body)
    if pr is not None:
        if not isinstance(pr, int) or isinstance(pr, bool) or pr < 1:
            raise BusError(f"invalid PR number: {pr!r}")
    if reply_to is not None and not (isinstance(reply_to, str) and ID_RE.match(reply_to)):
        raise BusError(f"invalid reply_to id: {reply_to!r}")
    identifier = message_id or uuid.uuid4().hex
    if not isinstance(identifier, str) or not ID_RE.match(identifier):
        raise BusError(f"invalid message id: {identifier!r}")
    return {
        "id": identifier,
        "from": sender,
        "to": recipient,
        "pr": pr,
        "type": message_type,
        "message": text,
        "reply_to": reply_to,
        "ts": time.time(),
    }


def append_message(message: dict, bus_dir=None) -> Path:
    """Append one message to its recipient's mailbox atomically.

    The whole message is one JSONL line written with a single ``O_APPEND`` write
    while holding an exclusive ``flock``, so concurrent senders cannot interleave
    or truncate each other's lines.
    """
    for key in REQUIRED_KEYS:
        if key not in message:
            raise BusError(f"message is missing required key {key!r}")
    line = json.dumps(message, sort_keys=True, ensure_ascii=True)
    if "\n" in line:
        raise BusError("serialized message must be one line")
    path = mailbox_path(message["to"], bus_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as handle:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            handle.write(line + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        finally:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
    return path


def read_messages(agent: str, bus_dir=None, last=None):
    """Return the mailbox's messages in append order.

    A mailbox is append-only, so reading is a scan; a malformed line is reported
    rather than silently skipped, because a corrupted mailbox must not look like
    an empty one.
    """
    path = mailbox_path(agent, bus_dir)
    if not path.is_file():
        return []
    messages = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        try:
            messages.append(json.loads(raw))
        except json.JSONDecodeError as error:
            raise BusError(f"{path}:{number}: not valid JSON ({error.msg})") from error
    if last is not None:
        return messages[-last:]
    return messages


def registered_target(agent: str, bus_dir=None):
    """Return the tmux target the agent last registered, or None."""
    for message in reversed(read_messages(agent, bus_dir)):
        if message.get("type") == "REGISTERED":
            target = message.get("tmux_target")
            if isinstance(target, str) and TMUX_TARGET_RE.match(target):
                return target
    return None


def peers(bus_dir=None):
    """Return ``{agent: tmux_target-or-None}`` for every mailbox on the bus."""
    directory = _bus_dir(bus_dir)
    if not directory.is_dir():
        return {}
    found = {}
    for path in sorted(directory.glob("*.jsonl")):
        agent = path.stem
        if AGENT_RE.match(agent):
            found[agent] = registered_target(agent, bus_dir)
    return found


# --------------------------------------------------------------------------- #
# tmux notification path
# --------------------------------------------------------------------------- #


def tmux_available() -> bool:
    return shutil.which("tmux") is not None


def _tmux(args, timeout=10):
    try:
        result = subprocess.run(["tmux", *args], capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.SubprocessError):
        return []
    if result.returncode != 0:
        return []
    return [line for line in result.stdout.splitlines() if line.strip()]


def list_panes():
    """Return tmux sessions and panes, or an empty result when tmux is absent."""
    if not tmux_available():
        return {"available": False, "sessions": [], "panes": []}
    return {
        "available": True,
        "sessions": _tmux(["list-sessions", "-F", "#{session_name}"]),
        "panes": _tmux(["list-panes", "-a", "-F", "#{session_name}:#{window_index}.#{pane_index}"]),
    }


def _capture(target: str) -> str:
    try:
        result = subprocess.run(["tmux", "capture-pane", "-t", target, "-p"], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return ""
    return result.stdout if result.returncode == 0 else ""


def _last_nonempty_line(text: str) -> str:
    for line in reversed(text.splitlines()):
        if line.strip():
            return line
    return ""


def notify_pane(target: str, notice: str, *, settle_seconds: float = 4.0) -> str:
    """Inject a coordination notice into a pane and verify it was delivered.

    The text is typed, Enter is sent in a *separate* call, and the pane is then
    captured and compared with its prior content. A previous lesson on this host
    is that ``send-keys`` returning success proves nothing: the text can sit
    unsent on the input line.

    The confirmation is deliberately two-part. A pane that did not change is
    unconfirmed. A pane whose *current input line* still holds the notice is
    unconfirmed as well — the terminal echoes whatever was typed, so the notice
    legitimately remains visible in scrollback after a successful submit; what
    distinguishes the two cases is whether the notice is still on the line the
    prompt is waiting on.

    Only this module's own generated notice text is ever injected; a peer message
    body is never typed into another session's terminal.
    """
    if not TMUX_TARGET_RE.match(target or ""):
        return "invalid-target"
    if not tmux_available():
        return "tmux-absent"
    before = _capture(target)
    if not before:
        return "unknown-pane"
    typed = subprocess.run(["tmux", "send-keys", "-t", target, "-l", notice], capture_output=True, text=True)
    if typed.returncode != 0:
        return "send-failed"
    time.sleep(1)
    entered = subprocess.run(["tmux", "send-keys", "-t", target, "Enter"], capture_output=True, text=True)
    if entered.returncode != 0:
        return "enter-failed"
    time.sleep(settle_seconds)
    after = _capture(target)
    if after == before:
        return "unconfirmed-unchanged"
    if notice in _last_nonempty_line(after):
        return "unconfirmed-on-input-line"
    return "confirmed"


def notify_message(recipient: str, bus_dir=None) -> str:
    """Wake a peer's registered pane with a mailbox notice, or degrade cleanly."""
    target = registered_target(recipient, bus_dir)
    if target is None:
        return "mailbox-only-no-registration"
    if not tmux_available():
        return "mailbox-only-tmux-absent"
    notice = f"Coordination message available in {_bus_dir(bus_dir) / f'{recipient}.jsonl'}"
    return notify_pane(target, notice)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #


def _cmd_send(args) -> int:
    message = build_message(
        sender=args.sender,
        recipient=args.to,
        message_type=args.type,
        body=args.message,
        pr=args.pr,
        reply_to=args.reply_to,
    )
    path = append_message(message, args.bus_dir)
    notice = "no-notify" if args.no_notify else notify_message(args.to, args.bus_dir)
    print(f"appended id={message['id']} mailbox={path}")
    print(f"notify={notice}")
    return 0


def _cmd_read(args) -> int:
    messages = read_messages(args.agent, args.bus_dir, last=args.last)
    for message in messages:
        print(json.dumps(message, sort_keys=True))
    if not messages:
        print(f"# mailbox {mailbox_path(args.agent, args.bus_dir)} is empty or new")
    return 0


def _cmd_peers(args) -> int:
    for agent, target in peers(args.bus_dir).items():
        print(f"{agent}\ttmux={target or '-'}")
    panes = list_panes()
    print(f"# tmux available={panes['available']} sessions={','.join(panes['sessions']) or '-'}")
    return 0


def _cmd_register(args) -> int:
    if args.tmux_target and not TMUX_TARGET_RE.match(args.tmux_target):
        raise BusError(f"invalid tmux target: {args.tmux_target!r}")
    message = build_message(
        sender=args.agent,
        recipient=args.agent,
        message_type="REGISTERED",
        body=args.message or f"{args.agent} online",
        pr=args.pr,
    )
    message["tmux_target"] = args.tmux_target or None
    append_message(message, args.bus_dir)
    print(f"registered agent={args.agent} tmux_target={args.tmux_target or '-'}")
    return 0


def main(argv) -> int:
    parser = argparse.ArgumentParser(description="Host-local liaison bus (append-only mailboxes).")
    parser.add_argument("--bus-dir", default=None, help=f"bus directory (default {DEFAULT_BUS_DIR})")
    sub = parser.add_subparsers(dest="command", required=True)

    send = sub.add_parser("send", help="append one coordination message")
    send.add_argument("--from", dest="sender", required=True)
    send.add_argument("--to", required=True)
    send.add_argument("--type", required=True)
    send.add_argument("--message", required=True)
    send.add_argument("--pr", type=int, default=None)
    send.add_argument("--reply-to", default=None)
    send.add_argument("--no-notify", action="store_true", help="append without waking the peer pane")
    send.set_defaults(func=_cmd_send)

    read = sub.add_parser("read", help="print a mailbox")
    read.add_argument("--agent", required=True)
    read.add_argument("--last", type=int, default=None)
    read.set_defaults(func=_cmd_read)

    register = sub.add_parser("register", help="announce this session's logical name and pane")
    register.add_argument("--agent", required=True)
    register.add_argument("--tmux-target", default=None, help="e.g. revocompute:0.0")
    register.add_argument("--message", default=None)
    register.add_argument("--pr", type=int, default=None)
    register.set_defaults(func=_cmd_register)

    listing = sub.add_parser("peers", help="list mailboxes and announced panes")
    listing.set_defaults(func=_cmd_peers)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except BusError as error:
        print(f"bus refuses request: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
